resources:
  repositories:
    - repository: electricShine
      type: github
      name: chasemc/electricShine
      endpoint: chasemc

jobs:
  - template: tests/templates/azure-tidyverse.yml@electricShine
